sudo: false

language: go

go:
 - 1.3.3
 - 1.4.1
 - tip

env:
  global:
  - secure: "PXt6fucUeI+eToxV+6lxwVZQWRZ/QLe/rexgPHUMBHcuevQFjRPZ3lcSCcKr9onLkb7REdDZj4Pct2zojPHtzvLV6QBl8LOF0QiGF+NmIZqhJMcJsEU476hKMuxotPMj6zKVhbRFKp/K7NmzezhMbkJembZhA4CMIZf+Buu6cqs="

before_install:
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
 - go get github.com/mattn/goveralls

script:
 - go get -d -t -v ./...
 - go build -v ./...
 - go test -v ./...
 - diff <(gofmt -d .) <("")
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash test-coverage.sh; fi

after_failure: failure

notifications:
  email:
    recipients:
      - jonathan.lawlor@gmail.com
    on_success: change
    on_failure: always
