language: go

env:
  global:
  - secure: "CN8poRl+k/ZlGWxIYuWj0XLaJuSfTe6xPAMtz/Vyos34fnsZ/GltCFvCw8+nuWY/ue0v5UGYq2tZm8e+GY6pwbvzX2lbn+EbpC6xdbbGZ+I434LPrUHIpWhohw1D8fDvvB2G/mZ95MW+cJdhCt7sT2UvADRR5CWxSceHKr573dg="

go:
 - 1.4.2
 - tip
 - 1.3.3

before_install:
 - sudo apt-get update -qq
 - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
 - go get github.com/mattn/goveralls


install:
 - go get github.com/gonum/floats
 - go get github.com/gonum/blas
 - go get gopkg.in/check.v1

script:
 - go get -d -t -v ./...
 - go build -x -v ./...
 - go test -tags bounds -x -v ./...
 - diff <(gofmt -d .) <("")
 - if [[ $TRAVIS_SECURE_ENV_VARS = "true" ]]; then bash test-coverage.sh; fi
 

after_failure: failure

notifications:
  email:
    recipients:
      - jonathan.lawlor@gmail.com
    on_success: change
    on_failure: always
