language: go

go:
 - release
 - tip

script:
 - go get -d -v ./...
 - go build -v ./...
 - go test -v ./...
 - diff <(gofmt -d .) <("") 

after_failure: failure

notifications:
  email:
    recipients:
      - jonathan.lawlor@gmail.com
    on_success: change
    on_failure: always
