language: go

go:
 - release
 - tip

 script:
  - go get -d -v ./...
  - go build -x -v ./...
  - go test -x -v ./...
  - diff <(gofmt -d .) <("")

 after_failure: failure
 after_error: failure

 notifications:
   email:
     recipients:
       - jonathan.lawlor@gmail.com
     on_success: change
     on_failure: always
